apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-file
  name: moh-site
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
