apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: apline-git
spec:
  lookupPolicy:
    local: false
  tags:
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source