kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: apline-git
  labels:
    name: apline-git
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'apline-git:latest'
  resources: {}
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: artifacts.developer.gov.bc.ca/docker-remote/alpine
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/alpine-docker/git.git'
  runPolicy: Serial
