apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: smk-site-base
  name: smk-base
spec:
  output:
    to:
      kind: ImageStreamTag
      name: smk-base:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM docker-remote.artifacts.developer.gov.bc.ca/alpine:3.8
      USER root
      ENV ENABLE_TELEMETRY="false"
      WORKDIR /app
      RUN apk add --no-cache git openssh-client \
       && adduser -S smk \
       && chown -R smk:0 /app && chmod -R 770 /app
      USER smk
      EXPOSE 8080
      CMD ["/go/caddy", "-quic", "--conf", "/conf/Caddyfile"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      pullSecret:
        name: artifactory-creds
    type: Docker
  triggers: []

